### ISSUE TITLE
Not every protocol upgrade neewds to be a hard fork

### ISSUE THREAD

**Issue by sgeisler** [BlocksizeProposals/BlocksizeProposals.github.io#4]
Nearly every protocol upgrade/feature can be achieved by hard or by soft fork. Therefore the listed proposals should be distinguished by their backwards compatibility.

**Comment by zander** [comment]
You are writing in the block size proposals repo, which is a menu on how to fix the block size limit.

As the block size limit is a consensus rule, 100% of the ways to solve the block size limit are going to need to change the consensus rules. There are other proposals, many of them, but when they do not fix the block size limit, they are off topic for this site.

Your pull request that marks everything as a hard fork therefore doesn't add anything except confusion.

I'm sorry, I don't agree with your thinking here.

**Comment by sgeisler** [comment]
Why don't you see the extension blocks proposal as a block size increase? It effectively makes blocks bigger (at least for the upgraded nodes) and allows more transactions to happen per block.

**Comment by zander** [comment]
> Why don't you see the extension blocks proposal as a block size increase? It effectively makes blocks bigger 

The extension blocks proposal is a great idea, and while I have not seen any implementation for it that could be used by the majority of the network, it is also a great answer to the segwit part that tries to increase the throughput.

I'm going to artificially draw the line at the fact that ext-blocks doesn't change the block size. It doesn't change the consensus rule for the block size limit.

**Comment by sgeisler** [comment]
Ok, I can live with this reasoning. But at least you should correct the first sentence:

> Should you consider a protocol upgrade in Bitcoin that allows the coin to continue organic growth and more customers, then this is the right place to come to.

Because this is not **the** right place to come to if it only explains a strict subset of the proposed solutions to the problems caused by the 1MB block size limit.
